# math este un modul built-in

In [1]:
import math

In [2]:
math.sqrt(64)

8.0

In [3]:
math.pi

3.141592653589793

# numpy este un modul care trebuie instalat

In [4]:
import numpy as np

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [7]:
arr = np.array([10, 123, 131, 230])
arr, type(arr)

(array([ 10, 123, 131, 230]), numpy.ndarray)

In [8]:
arr = np.array([10, 123, 131, 23.3210])
arr, type(arr)

(array([ 10.   , 123.   , 131.   ,  23.321]), numpy.ndarray)

In [9]:
arr = np.array([10, 123, 131, 23.3210])
arr, type(arr), arr.dtype

(array([ 10.   , 123.   , 131.   ,  23.321]), numpy.ndarray, dtype('float64'))

In [10]:
arr = np.array([10, 123, 131, 230])
arr, type(arr), arr.dtype

(array([ 10, 123, 131, 230]), numpy.ndarray, dtype('int64'))

In [12]:
arr = np.array([10, 123, 131, 230, 31.99, "hello"])
arr, type(arr), arr.dtype

(array(['10', '123', '131', '230', '31.99', 'hello'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [13]:
arr = np.array([10, 123, 131, 230, 31.99, "hello", [321, 321]])
arr, type(arr), arr.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7,) + inhomogeneous part.

In [14]:
arr = np.array([
            [10, 123, 131, 230], [31.99, "hello", 321, 321]])
arr, type(arr), arr.dtype

(array([['10', '123', '131', '230'],
        ['31.99', 'hello', '321', '321']], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [ ]:
arr = np.array([
            [10, 123, 131, 230], 
            [31.99, "hello", 321, 321]])
arr, arr.shape 

(array([['10', '123', '131', '230'],
        ['31.99', 'hello', '321', '321']], dtype='<U32'),
 (2, 4))

In [17]:
arr = np.array([
            [10, 123, 131, 230], 
            [31.99, "hello", 321, 32]])
arr, arr.shape 

(array([['10', '123', '131', '230'],
        ['31.99', 'hello', '321', '32']], dtype='<U32'),
 (2, 4))

In [18]:
arr.reshape((4,2))

array([['10', '123'],
       ['131', '230'],
       ['31.99', 'hello'],
       ['321', '32']], dtype='<U32')

In [19]:
arr = np.array([2, 4, 5, 10, 11, 12, 40, 50])
arr

array([ 2,  4,  5, 10, 11, 12, 40, 50])

# Fast mathematical operations over array

# 1. Operatii artimetice

In [20]:
arr - 2

array([ 0,  2,  3,  8,  9, 10, 38, 48])

In [21]:
arr

array([ 2,  4,  5, 10, 11, 12, 40, 50])

In [22]:
arr ** 2 

array([   4,   16,   25,  100,  121,  144, 1600, 2500])

In [24]:
another_arr = np.array([ 1,  1,  1, 1, 1, 1, 1])
another_arr

array([1, 1, 1, 1, 1, 1, 1])

In [25]:
arr - another_arr

ValueError: operands could not be broadcast together with shapes (8,) (7,) 

In [26]:
another_arr = np.array([ 1,  1,  1, 1, 1, 1, 1, 1])
another_arr

array([1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
arr - another_arr

array([ 1,  3,  4,  9, 10, 11, 39, 49])

# 2. Operatii logice

In [28]:
arr

array([ 2,  4,  5, 10, 11, 12, 40, 50])

In [29]:
arr > 10

array([False, False, False, False,  True,  True,  True,  True])

In [30]:
arr [ arr > 10]

array([11, 12, 40, 50])

In [31]:
conditie = arr > 10
arr [ conditie]

array([11, 12, 40, 50])

In [32]:
arr

array([ 2,  4,  5, 10, 11, 12, 40, 50])

In [33]:
conditie1 = arr > 5
conditie2 = arr % 2 == 0

arr [ conditie1 & conditie2]


array([10, 12, 40, 50])